### ISSUE TITLE
Composer create project does not work anymore with Composer 2.3.0+

### ISSUE THREAD

**Issue by pgrafe** [laminas/laminas-skeleton-installer#31]
### Bug Report

Init new [Laminas Skeleton](https://docs.laminas.dev/tutorials/getting-started/skeleton-application/)
composer create-project -s dev laminas/laminas-mvc-skeleton path/to/install

In Question.php line 39:
  [TypeError]
  Argument 1 passed to Symfony\Component\Console\Question\Question::__constru
  ct() must be of the type string, array given, called in phar:///var/www/com
  poser.phar/src/Composer/IO/ConsoleIO.php on line 273

#### Summary

Solution:
https://ibexdataservices.com/news_errors-installing-laminas-mvc-skeleton/

OptionalPackagesInstaller.php, Line 138: remove the opening bracket following the ‘=’ when setting the $question variable. Then, remove the closing bracket and the comma (around line 143).

Same file, same concept: remove the brackets and unnecessary comma from the $question variable set in line 169.

**Comment by Ocramius** [comment]
Can you check if this is caused by the upgrade from `composer/composer:2.2.9` to `composer/composer:2.3.0`?

**Comment by pgrafe** [comment]
> Can you check if this is caused by the upgrade from `composer/composer:2.2.9` to `composer/composer:2.3.0`?

Yes. I can confirm that it is working with composer 2.2.9 and broken with composer 2.3.0 and 2.3.3

**Comment by froschdesign** [comment]
I can confirm the problem with version 2.3.x.
Version 2.2.x works without errors.
